name: e2e

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        # Uncomment and replace with current `os` when windows-run bug is fixed
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Test
        run: npm t -- --collectCoverage e2e

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./test-reports/coverage
          env_vars: OS
          fail_ci_if_error: false
          flags: generator
          name: codecov-umbrella
          verbose: true
